---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azuremonitor-containers
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: azuremonitor-containers
  chart:
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    name: azuremonitor-containers
    version: 2.5.0
  values:
    omsagent:
      secret:
        wsid: 4eca127e-230d-4f08-8793-3c4289036900
        key: <key_place_holder>
      env:
        clusterId: /subscriptions/09af8f6f-d4e5-4b9d-950b-b7aa2e897477/resourceGroups/gangams-akse-arc-test-rg/providers/Microsoft.Kubernetes/connectedClusters/gangams-akse-arc-test
